varivel = input('Digite algo: ')
print('O tipo primitivo deste valor é:', type(varivel))
print('Só tem espaços ?', varivel.isspace())
print('É um numero ? ', varivel.isnumeric())
print('É alfabetico ?', varivel.isalpha())
print('É alphanumerico ?', varivel.isalnum())
print('Esta em maiscula ?', varivel.isupper())
print('Esta em minuscula ?', varivel.islower())
print('Esta capitalizada ?', varivel.istitle())